openapi: 3.0.3
info:
  title: Controle de Acesso - Area de TI
  version: 1.0.0
  description: >
    Este recurso nao introduz novos endpoints de API.
    O controle de acesso utiliza fluxos existentes de autenticacao e RBAC.
paths: {}
x-notes:
  - "Sem novos contratos de API. Reaproveita autorizacao existente."
