openapi: 3.0.3
info:
  title: RBAC Operacoes
  version: 0.1.0
servers:
  - url: /

paths:
  /api/me/permissions:
    get:
      summary: Retorna permissoes do usuario autenticado
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de permissoes e cargos do usuario
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserPermissionsResponse"
        "401":
          description: Usuario nao autenticado

  /api/me/navigation:
    get:
      summary: Retorna secoes/modulos permitidos para navegacao
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Secoes liberadas para o usuario
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NavigationResponse"
        "401":
          description: Usuario nao autenticado

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RoleSummary:
      type: object
      properties:
        name:
          type: string
          example: "Supervisor"
        department:
          type: string
          nullable: true
          example: "Operacoes"
        is_global:
          type: boolean
      required:
        - name
        - department
        - is_global

    Permission:
      type: string
      description: Codigo de permissao RBAC
      enum:
        - tickets:read
        - tickets:create
        - tickets:approve
        - tickets:triage
        - checklists:read
        - checklists:execute
        - checklists:configure
        - units:read
        - units:update
        - reports:read

    UserPermissionsResponse:
      type: object
      properties:
        user_id:
          type: string
        roles:
          type: array
          items:
            $ref: "#/components/schemas/RoleSummary"
        permissions:
          type: array
          items:
            $ref: "#/components/schemas/Permission"
      required:
        - user_id
        - roles
        - permissions

    NavigationResponse:
      type: object
      properties:
        sections:
          type: array
          items:
            type: string
            example: "Chamados"
      required:
        - sections
