openapi: 3.0.3
info:
  title: Visibilidade de Chamados do Gerente de Operacoes
  version: 1.0.0
  description: >
    Este ajuste nao cria novos endpoints.
    A visibilidade e a cadeia de aprovacao sao aplicadas nas consultas e fluxos existentes.
paths: {}
x-notes:
  - "Sem novos contratos de API. Reaproveita consultas e RBAC existentes."
