openapi: 3.0.3
info:
  title: Controle de acesso - unidades e checklists do supervisor
  version: 1.0.0
  description: >
    Este recurso nao introduz novos endpoints de API.
    O controle de acesso utiliza RBAC e consultas existentes (RPC/RLS).
paths: {}
x-notes:
  - "Sem novos contratos de API. Reaproveita fluxos existentes."
